# Generated by Django 3.1.2 on 2020-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('father', models.CharField(default='', max_length=122)),
                ('name2', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('phone1', models.CharField(max_length=12)),
                ('MhtcetAppNo', models.CharField(max_length=12)),
                ('MhtcetPercentile', models.CharField(max_length=12)),
                ('MhtcetRank', models.CharField(max_length=12)),
                ('JeeAppNo', models.CharField(max_length=12)),
                ('JeePercentile', models.CharField(max_length=12)),
                ('JeeRank', models.CharField(max_length=12)),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('CollegeName', models.CharField(max_length=122)),
                ('Percentage', models.CharField(max_length=12)),
                ('Aadhar', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
