# Generated by Django 3.1.2 on 2020-12-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Aadhar',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Address1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='CollegeName',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='JeeAppNo',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='JeePercentile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='JeeRank',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='MhtcetAppNo',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='MhtcetPercentile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='MhtcetRank',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Percentage',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='father',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone1',
        ),
    ]
