# Generated by Django 3.1.2 on 2020-12-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
