# Generated by Django 3.1.2 on 2020-12-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
